Update compose.yml

diff --git a/compose.yml b/compose.yml
--- a/compose.yml
+++ b/compose.yml
@@ -14,9 +14,16 @@ services:
       - ./env/smp.env
     ports:
       - "5223:5223"
+    command:
+      sh -c 'until [ -s /certificates/$ADDR.crt ] && [ -s /certificates/$ADDR.key ]; do
+        echo "waiting for TLS certificates to be available from ACME.sh";
+        sleep 5;
+        done;
+        exec /entry.sh'
     volumes:
       - ./simplex/server/config:/etc/opt/simplex
       - ./simplex/server/state:/var/opt/simplex
+      - ./coturn/certs:/certificates
     restart: unless-stopped
 
   xftp:
@@ -48,9 +55,20 @@ services:
     container_name: acme
     env_file:
       - ./env/acme.env
+    entrypoint: >
+      sh -c ' acme.sh --register-account -m "$EMAIL" || true; 
+        while true; do
+          if acme.sh --issue --force --dns dns_duckdns -d "$DOMAIN" --keylength ec-256; then 
+            acme.sh --install-cert -d "$DOMAIN" --fullchain-file /certificates/$DOMAIN.crt --key-file /certificates/$DOMAIN.key; echo "Sleeping before renewal cycle"; sleep 12h;
+          else
+            echo "Certificate issuing process failed. Retry in 2 minutes"
+            sleep 120;
+          fi
+        done
+      '
     volumes:
       - ./acme/account:/acme.sh
-      - ./coturn/certs:/certs
+      - ./coturn/certs:/certificates
       - ./coturn/hooks:/hooks
       - /var/run/docker.sock:/var/run/docker.sock
     restart: unless-stopped
